frr defaults traditional
hostname p2
no ipv6 forwarding
log file /var/log/frr/frr.log informational
log syslog informational
log commands
service integrated-vtysh-config
!
agentx
!
interface lo
 ip address 10.0.0.12/32
!
interface eth1
 ip address 10.0.12.6/30
!
interface eth2
 ip address 10.0.12.9/30
!
interface eth3
 ip address 10.0.12.38/30
!
interface eth4
 ip address 10.0.12.45/30
!
interface eth5
 ip address 10.0.12.58/30
!
mpls ldp
 router-id 10.0.0.12
 !
 address-family ipv4
  discovery transport-address 10.0.0.12
  !
  interface eth1
  !
  interface eth2
  !
  interface eth3
  !
  interface eth4
 exit-address-family
!
router ospf
 ospf router-id 10.0.0.12
 network 10.0.0.12/32 area 0
 network 10.0.12.4/30 area 0
 network 10.0.12.8/30 area 0
 network 10.0.12.36/30 area 0
 network 10.0.12.44/30 area 0
 network 10.0.12.56/30 area 0
 passive-interface lo
!
line vty
!
end
