frr defaults traditional
hostname leaf1
no ipv6 forwarding
log file /var/log/frr/frr.log informational
log syslog informational
log commands
service integrated-vtysh-config
!
agentx
!
vrf TENANT-A
 vni 5000
!
interface lo
 ip address 10.2.0.4/32
!
interface eth1
 ip address 10.2.12.10/30
!
interface eth2
 ip address 10.2.12.17/30
!
router bgp 65511
 bgp router-id 10.2.0.4
 no bgp ebgp-requires-policy
 neighbor 10.2.12.9 remote-as 65501
 neighbor 10.2.12.9 description spine1
 neighbor 10.2.12.18 remote-as 65502
 neighbor 10.2.12.18 description spine2
 !
 address-family ipv4 unicast
  network 10.2.0.4/32
  neighbor 10.2.12.9 activate
  neighbor 10.2.12.18 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.2.12.9 activate
  neighbor 10.2.12.18 activate
  advertise-all-vni
  vni 10110
   rd 10.2.0.4:10110
   route-target import 65000:10110
   route-target export 65000:10110
  exit-vni
 exit-address-family
!
router bgp 65511 vrf TENANT-A
 bgp router-id 10.2.0.4
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.2.0.4:5000
  route-target import 65000:5000
  route-target export 65000:5000
 exit-address-family
!
line vty
!
end
