frr defaults traditional
hostname leaf2
no ipv6 forwarding
log file /var/log/frr/frr.log informational
service integrated-vtysh-config
!
agentx
!
vrf TENANT-A
 vni 5000
!
interface lo
 ip address 10.2.0.5/32
!
interface eth1
 ip address 10.2.12.14/30
!
interface eth2
 ip address 10.2.12.21/30
!
router bgp 65512
 bgp router-id 10.2.0.5
 neighbor 10.2.12.13 remote-as 65502
 neighbor 10.2.12.13 description spine2
 neighbor 10.2.12.22 remote-as 65501
 neighbor 10.2.12.22 description spine1
 !
 address-family ipv4 unicast
  network 10.2.0.5/32
  neighbor 10.2.12.13 activate
  neighbor 10.2.12.22 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.2.12.13 activate
  neighbor 10.2.12.22 activate
  advertise-all-vni
  vni 10120
   rd 10.2.0.5:10120
   route-target import 65000:10120
   route-target export 65000:10120
  exit-vni
 exit-address-family
!
router bgp 65512 vrf TENANT-A
 bgp router-id 10.2.0.5
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.2.0.5:5000
  route-target import 65000:5000
  route-target export 65000:5000
 exit-address-family
!
line vty
!
end
