frr defaults traditional
hostname p1
no ipv6 forwarding
log file /var/log/frr/frr.log informational
service integrated-vtysh-config
!
agentx
!
interface lo
 ip address 10.0.0.11/32
!
interface eth1
 ip address 10.0.12.2/30
!
interface eth2
 ip address 10.0.12.5/30
!
interface eth3
 ip address 10.0.12.30/30
!
interface eth4
 ip address 10.0.12.41/30
!
interface eth5
 ip address 10.0.12.49/30
!
interface eth6
 ip address 10.0.12.54/30
!
mpls ldp
 router-id 10.0.0.11
 !
 address-family ipv4
  discovery transport-address 10.0.0.11
  !
  interface eth1
  !
  interface eth2
  !
  interface eth3
  !
  interface eth4
  !
  interface eth5
 exit-address-family
!
router ospf
 ospf router-id 10.0.0.11
 network 10.0.0.11/32 area 0
 network 10.0.12.0/30 area 0
 network 10.0.12.4/30 area 0
 network 10.0.12.28/30 area 0
 network 10.0.12.40/30 area 0
 network 10.0.12.48/30 area 0
 network 10.0.12.52/30 area 0
 passive-interface lo
!
line vty
!
end
