frr defaults traditional
hostname border1
no ipv6 forwarding
log file /var/log/frr/frr.log informational
service integrated-vtysh-config
!
agentx
!
vrf TENANT-A
 vni 5000
!
interface lo
 ip address 10.2.0.1/32
!
interface eth1
 vrf TENANT-A
 ip address 100.64.2.2/30
!
interface eth2
 vrf TENANT-A
 ip address 100.64.2.6/30
!
interface eth3
 ip address 10.2.12.1/30
!
interface eth4
 ip address 10.2.12.5/30
!
router bgp 65513
 bgp router-id 10.2.0.1
 neighbor 10.2.12.2 remote-as 65501
 neighbor 10.2.12.2 description spine1
 neighbor 10.2.12.6 remote-as 65502
 neighbor 10.2.12.6 description spine2
 !
 address-family ipv4 unicast
  network 10.2.0.1/32
  neighbor 10.2.12.2 activate
  neighbor 10.2.12.6 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.2.12.2 activate
  neighbor 10.2.12.6 activate
 exit-address-family
!
router bgp 65513 vrf TENANT-A
 bgp router-id 10.2.0.1
 no bgp ebgp-requires-policy
 neighbor 100.64.2.1 remote-as 65000
 neighbor 100.64.2.1 description isp-pe2-circuitA
 neighbor 100.64.2.5 remote-as 65000
 neighbor 100.64.2.5 description isp-pe4-circuitB
 !
 address-family ipv4 unicast
  neighbor 100.64.2.1 activate
  neighbor 100.64.2.5 activate
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.2.0.1:5000
  route-target import 65000:5000
  route-target export 65000:5000
 exit-address-family
!
line vty
!
end
