frr defaults traditional
hostname p3
no ipv6 forwarding
log file /var/log/frr/frr.log informational
log syslog informational
log commands
service integrated-vtysh-config
!
agentx
!
interface lo
 ip address 10.0.0.13/32
!
interface eth1
 ip address 10.0.12.14/30
!
interface eth2
 ip address 10.0.12.17/30
!
interface eth3
 ip address 10.0.12.26/30
!
interface eth4
 ip address 10.0.12.42/30
!
mpls ldp
 router-id 10.0.0.13
 !
 address-family ipv4
  discovery transport-address 10.0.0.13
  !
  interface eth1
  !
  interface eth2
  !
  interface eth3
  !
  interface eth4
 exit-address-family
!
router ospf
 ospf router-id 10.0.0.13
 network 10.0.0.13/32 area 0
 network 10.0.12.12/30 area 0
 network 10.0.12.16/30 area 0
 network 10.0.12.24/30 area 0
 network 10.0.12.40/30 area 0
 passive-interface lo
!
line vty
!
end
