frr defaults traditional
hostname spine2
no ipv6 forwarding
log file /var/log/frr/frr.log informational
service integrated-vtysh-config
!
agentx
!
interface lo
 ip address 10.2.0.3/32
!
interface eth1
 ip address 10.2.12.6/30
!
interface eth2
 ip address 10.2.12.13/30
!
interface eth3
 ip address 10.2.12.18/30
!
route-map UNCHANGED-NHOP permit 10
 set ip next-hop unchanged
!
router bgp 65502
 bgp router-id 10.2.0.3
 no bgp ebgp-requires-policy
 neighbor 10.2.12.5 remote-as 65513
 neighbor 10.2.12.5 description border1
 neighbor 10.2.12.14 remote-as 65512
 neighbor 10.2.12.14 description leaf2
 neighbor 10.2.12.17 remote-as 65511
 neighbor 10.2.12.17 description leaf1
 !
 address-family ipv4 unicast
  network 10.2.0.3/32
  neighbor 10.2.12.5 activate
  neighbor 10.2.12.14 activate
  neighbor 10.2.12.17 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.2.12.5 activate
  neighbor 10.2.12.14 activate
  neighbor 10.2.12.17 activate
  neighbor 10.2.12.5 route-map UNCHANGED-NHOP out
  neighbor 10.2.12.14 route-map UNCHANGED-NHOP out
  neighbor 10.2.12.17 route-map UNCHANGED-NHOP out
 exit-address-family
!
line vty
!
end
