frr defaults traditional
hostname br-dist1
no ipv6 forwarding
log file /var/log/frr/frr.log informational
service integrated-vtysh-config
!
agentx
!
interface lo
 ip address 10.1.0.2/32
!
interface eth2
 ip address 10.1.2.1/30
!
interface eth3
 ip address 10.1.1.1/30
!
interface eth1.10
 ip address 10.1.10.2/24
 vrrp 10 ip 10.1.10.1
 vrrp 10 priority 110
 vrrp 10 advertisement-interval 100
 no vrrp 10 shutdown
!
interface eth1.20
 ip address 10.1.20.3/24
 vrrp 20 ip 10.1.20.1
 vrrp 20 priority 90
 vrrp 20 advertisement-interval 100
 no vrrp 20 shutdown
!
router ospf
 ospf router-id 10.1.0.2
 network 10.1.0.2/32 area 0
 network 10.1.1.0/30 area 0
 network 10.1.2.0/30 area 0
 network 10.1.10.0/24 area 0
 network 10.1.20.0/24 area 0
 passive-interface lo
 passive-interface eth1.10
 passive-interface eth1.20
!
line vty
!
end
